# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-12-14 11:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restuarants', '0005_auto_20181207_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='restuarantlocation',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
