# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-11 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restuarants', '0003_auto_20180809_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='restuarantlocation',
            name='category',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
