# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-11 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restuarants', '0004_restuarantlocation_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restuarantlocation',
            name='category',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
