# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-11 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restuarants', '0006_restuarantlocation_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='restuarantlocation',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='restuarantlocation',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
